spring:
  profiles:
    active: develop
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
liquibase:
  change-log: classpath:db/changelog/db.changelog-master.xml
  enabled: false
security:
  basic:
    enabled: true
---
spring:
  profiles: develop
  datasource:
    username: postgres
    password: dima1234
    url: jdbc:postgresql://127.0.0.1:5432/postgres
security:
  user:
    password: 12NasTya33
    name: nastya
    role: USER